#!bin/bash
clear


echo "════════════════════════ "
echo "Author :TRIO CHANNEL "
echo "Youtube:TRIO CHANNEL "
echo "════════════════════════ "
figlet TELp | lolcat
echo '
[1], Spam Call
[2], Exit Tools                                            '

echo
read -p "Masukan Pilihan Anda : " pil
if [[ $pil == 1 ]]; then
read -p "Masukan No Target : " nomor
link="https://id.jagreward.com/member/verify-mobile/$nomor"
curl -s $link
else
echo "Trima Kasih Sudah Menggunakan Tools ini"
exit
fi
echo
